### ISSUE TITLE
Session does not persist with reactive front-ends like React / React Admin

### ISSUE THREAD

**Issue by TatanParker** [alex-oleshkevich/starsessions#13]
Dear Alex!

Im using you SessionMiddleware, and for static fronts, like Swagger UI in FastAPI, works nice, the session (session_id) persists, but when I use a React frontend, the session is being regenerated everytime, so I cannot control it and persist data and so on.

Is there something that Im missing?

My desire is to, in someway, persist the session when the actions are performed from the same user agent (same browser i.e.). I confirm that, this behaviour exactly ocurrs with static ones but reactive ones is creating a new id (the middleware) in each request.

Thanks in advance!

**Comment by alex-oleshkevich** [comment]
Make sure:
1. your browser sends session cookie
2. the `path` is not restricted by cookie security rules
3. subdomain, if any, is not restricted by cookie security rules
4. check `same_site` rule
