### ISSUE TITLE
Set frontend cookies to expire from backend

### ISSUE THREAD

**Issue by RamiAwar** [alex-oleshkevich/starsessions#16]
Hey @alex-oleshkevich !

Isn't it possible to clear the frontend session cookie for most browsers?

By setting it to an empty value and an expiry date that has already passed, most browsers would know to clear it.

Even if the browser didn't clear it, by setting it to an empty value it is no longer valid.
```Set-Cookie: token=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT```

We could have this take place as part of `session.clear()`. What do you think?

**Comment by RamiAwar** [comment]
Oh wait, you already do that?

```
elif scope["session"].is_loaded and scope["session"].is_empty:
                    if not self.path or self.path and scope['path'].startswith(self.path):
                        # no interactions to session were done
                        headers = MutableHeaders(scope=message)
                        header_value = "{}={}; {}".format(
                            self.session_cookie,
                            f"null; path={path}; expires=Thu, 01 Jan 1970 00:00:00 GMT;",
                            self.security_flags,
                        )
                        headers.append("Set-Cookie", header_value)
```

**Comment by RamiAwar** [comment]
I don't fully understand how this works tbh. When do we send this updated empty expired cookie exactly?

**Comment by RamiAwar** [comment]
I think this comment from the cookie backend is what confused me and made me thing we don't do that.

Why isn't it possible to do in this case like we do above?
```python
    async def remove(self, session_id: str) -> None:
        """Session data stored on client side - no way to remove it."""
```

**Comment by alex-oleshkevich** [comment]
>  I don't fully understand how this works tbh. When do we send this updated empty expired cookie exactly?

It removes session cookie when session has no data https://github.com/alex-oleshkevich/starsessions/blob/master/starsessions/middleware.py#L73

> Why isn't it possible to do in this case like we do above? Set it to expired, set the data to empty.

This looks like a missing feature or a bug. Let me think more on it.

**Comment by RamiAwar** [comment]
Okay, I'm willing to contribute it along with some other stuff I plan on doing this weekend, if you think this is a missing feature that is.

**Comment by alex-oleshkevich** [comment]
It's pretty obvious, that storage has to be cleared at session termination. As for now, the storage gets cleared only when we call `await session.delete()` manually. We should also call `delete` in the middleware.
