### ISSUE TITLE
starsessions 2.0

### ISSUE THREAD

**Issue by alex-oleshkevich** [alex-oleshkevich/starsessions#18]
What I'd like to see in the next release:

1. automatic session loading (probably via `loop.run_until_complete`)
2. move serializers to middleware (now they are in backends)
3. require explicit backend and remove `secret_key` from middleware arguments
4. ability to encrypt session contents, this is mandatory when using shared Redis instances
5. `regenerate_id` should be a utility function, not a part of `Session` class because this makes mypy sad: `request.session.regenerate_id()` vs `new_id = regenerate_id(request.session)`
6. cleanup `Session` class interface: consider removing all non-mapping methods from it, they are not compatible with Starlette's session interface
7. change `Backend.write` signature to `async def write(self, session_id: str, data: typing.Dict) -> str`, session_id to be required

Anything else?

**Comment by RamiAwar** [comment]
Let's create a milestone out of this and track each one as an issue in a Github project maybe.

I think there are a lot of nice-to-haves we can choose from frontend frameworks like ExpressJS which are considered industry standard too.
