### ISSUE TITLE
Redis backend exists fails on session_id None

### ISSUE THREAD

**Issue by RamiAwar** [alex-oleshkevich/starsessions#22]
So I'm not sure about this one being part of starsessions, but it would definitely make things easier for developers.

If someone ever tries to lookup a session_id that is `None`, then the backend would fail to get the redis key.

One could argue that the responsibility falls on the developer to make sure the session_id isn't None before checking if it exists.
But it also makes sense to return False if the session_id=None doesn't exist.

What do you think? @alex-oleshkevich 

```python
    async def exists(self, session_id: str) -> bool:
         + if session_id is None:
         +   return False

        result = await self._connection.exists(self.get_redis_key(session_id))
        return result > 0
  ```

**Comment by alex-oleshkevich** [comment]
Maybe we can always generate session_id? What are possible side effects?

**Comment by alex-oleshkevich** [comment]
Let's check how other frameworks (non-python too) handle that.

**Comment by RamiAwar** [comment]
The real problem is in get_redis_key I think. If session_id is None, then get_redis_key will always fail since it calls a callable that expects a string as an argument.

This happens naturally when the session expires on the frontend and no cookie is sent back to the API. 

The expected response would be to just not find the session and clear the session on the backend and frontend. Backend clear will do nothing (empty session id, doesn't exist). Frontend clear will send an expired cookie back which will clear it.


Proposed solution: maybe we should change get_redis_key to:
```python
    def get_redis_key(self, session_id: str) -> str:
        if session_id is None:
            session_id = ""

        if self._redis_key_func:
            return self._redis_key_func(session_id)
        else:
            return session_id
```

Otherwise we'd have to add this NoneType check to every single backend method.

**Comment by alex-oleshkevich** [comment]
Yes, let's do it like that 
```
if session_id is None:
     return False
```
We really have nothing to do if session_id is None.

**Comment by RamiAwar** [comment]
So you mean in get_redis_key we just return "" instead of what I did above?
```python
    def get_redis_key(self, session_id: str) -> str:
        if session_id is None:
            return ""
```

**Comment by alex-oleshkevich** [comment]
Better to patch `read`, `exists`, and `remove` to not fail when session_id is None. 
* `read` will return `{}`
* `exists` will return `False`
* `remove` will return nothing

I see it as an example to other devs willing to make their own backends. `get_redis_key` is too specific to Redis.

I give a green light to this ;)

**Comment by RamiAwar** [comment]
Ah I see what you mean. Yes I agree in this case, better keep it flexible.

Will submit a PR soon :)
