### ISSUE TITLE
Separate rolling time extension from lifetime

### ISSUE THREAD

**Issue by RamiAwar** [alex-oleshkevich/starsessions#52]
First of all, super impressed by all the work you did since a couple of months, that's insane! Still trying to read through the changes.

Do you think it makes sense to provide two config values for the session middleware? In my use case, I'd like to give a session lifetime of 1 day, but if the user happens to be mid-session and near that deadline, then I'd want to extend his session by 5 minutes just so we don't cut them off. But after 5 minutes they're auto-logged out.

Right now the extension would be for another full day which is too permissive maybe.

**Comment by alex-oleshkevich** [comment]
This is a very specific use case, I am not sure if someone else could want it. Another argument will add an extra complexity to the middleware. 

I would recommend you to go with short living rolling sessions and see how it fits your needs.
