### ISSUE TITLE
Request.session should be typed

### ISSUE THREAD

**Issue by ananthb** [alex-oleshkevich/starsessions#53]
If I access request.session in my code after using the auto-load middleware, mypy throws up an error about a non-existent attribute:

```shell
rmp.py:109: error: "Request" has no attribute "sesssion"
```

**Comment by alex-oleshkevich** [comment]
Is impossible as Httpconnection ( the base of Request) explicitly defines it in the code.
Can you provide a full code snippet?

**Comment by ananthb** [comment]
I'm an idiot, and it was a typo. My bad!

<img width="415" alt="Screenshot 2022-09-18 at 10 26 23 PM" src="https://user-images.githubusercontent.com/3133350/190919087-c3ab9539-bc93-4f22-ab09-6c7db7605b77.png">
