### ISSUE TITLE
aioredis dependency

### ISSUE THREAD

**Issue by euri10** [alex-oleshkevich/starsessions#55]
Hi @alex-oleshkevich 
I just realize we depend on aioredis, it's been a while since I tracked the "complicate" state of redis pythoin libraries but it seemed to me that this one is pretty mych abandonned and that it's async part is now available on https://github.com/redis/redis-py
would you be fancy swithcing dependencies ?

**Comment by alex-oleshkevich** [comment]
Good news actually!
