### ISSUE TITLE
Session does not work when mounting routes

### ISSUE THREAD

**Issue by RufusNA** [alex-oleshkevich/starsessions#60]
If mounting routes from a different app ("/auth) the session only works for that mount or route and not when for example redirected to "/" where the session or the cookie containing the session id is removed?

Edit: I had to set `cookie_path="/"` on `SessionMiddleware`. Is that correct?

**Comment by alex-oleshkevich** [comment]
Yes, the issue is with Mount class. There is an issue in Starlette repo about it.
