### ISSUE TITLE
"null" Session Id when using RedisBackend and InMemoryBackend

### ISSUE THREAD

**Issue by Grustamli** [alex-oleshkevich/starsessions#7]
Session ID is shown as null when I use RedisBackend. It is also same for InMemoryBackend. However, Cookie backend works fine.

**Comment by Grustamli** [comment]
The issue seems to arise on this line: https://github.com/alex-oleshkevich/starsessions/blob/6bd258a0f94d30b6ec4a8da41910f97c5dabbe54/starsessions/middleware.py#L46
I am using Fastapi, btw.

**Comment by alex-oleshkevich** [comment]
can you share a code example for more context?

**Comment by Grustamli** [comment]
Please see below.

```python
app = FastAPI()
app.include_router(router) # Simple API router

app.add_middleware(SessionMiddleware, backend=RedisBackend(settings.redis_url), autoload=True)
```
I checked the `generate_id()` function and it is working as intended. However, as I posted above `self.session_cookie` returns `null`

**Comment by Grustamli** [comment]
Sorrry not the `self.session_cookie` but `connection.cookies.get(self.session_cookie, None)` returns `null`.

**Comment by alex-oleshkevich** [comment]
Also attach an example of your view function where you call this code.

The session id will be generated by the session middleware if empty. This happens when response is being sent.

**Comment by Grustamli** [comment]
This is the only view where I write to the session.

```python
@router.post("/password/request", status_code=status.HTTP_202_ACCEPTED)
async def reset_request(
    request: Request,
    background_tasks: BackgroundTasks,
    email: str = Body(..., embed=True),
):
    otp = generate_otp()
    otp_expires_at = dt.datetime.now() + dt.timedelta(seconds=settings.otp_valid_for)

    request.session[SESSION_KEY_OTP] = otp
    request.session[SESSION_KEY_OTP_EXPIRES_AT] = otp_expires_at.timestamp()

    background_tasks.add_task(email_otp, email, otp)

```

**Comment by alex-oleshkevich** [comment]
Looks like that is all fine. The session ID will be generated once the response is sent and will be available on the next request. 
In the browser's dev tools, do you see a random string in place of the "session" cookie or just None?

**Comment by Grustamli** [comment]
When I use CookieBackend I see session key and value. However, in any of the other backends cookie is returned empty. I use Insomnia to test it. 
It should generate and ID on first write but when I debug the RedisBackend and session ID is saved as actual string with "null" value. This is because of the line I posted above where `connection.cookies.get(self.session_cookie, None)` picks `null` string value from an empty cookie. Could you please check it on your side, too?

**Comment by alex-oleshkevich** [comment]
yes, sure. thanks for report.

**Comment by alex-oleshkevich** [comment]
1. can you also make sure that is it not related to https://github.com/encode/starlette/issues/1261 ?
2. run [examples/redis.py](examples/redis.py) locally on a different port, goto `/set`, and check if the cookie is set. 

I tested locally and all works fine.

>> When I use CookieBackend I see session key and value
CookieBackend is different. The ID here is encrypted cookie content so it is always available.

**Comment by Grustamli** [comment]
I will check and report back. Thank you!

**Comment by Grustamli** [comment]
After checking on a different machine, RedisBackend works fine. Session ID is set as expected. Now, I have to investigate why it didn't work before. Sorry for bothering )
